#!/usr/bin/env bash
# This script shows sub-domain info

get_subdomain() {
  record_type="$(dig "$2"."$1" +noall +answer | awk '{ print $4 }')"
  destination_ip="$(dig "$2"."$1" +noall +answer | awk '{ print $5 }')"
  echo "The subdomain ${2} is a ${record_type} record and points to ${destination_ip}"
}

# check, if number of arguments is 2
if [ "$#" -ne 2 ]; then
    get_subdomain "$1" "www"
    get_subdomain "$1" "lb-01"
    get_subdomain "$1" "web-01"
    get_subdomain "$1" "web-02"
else
    get_subdomain "$1" "$2"
fi
