#!/usr/bin/env bash
# Define IP addresses
LB_IP="lb-01-IP-address"
WEB1_IP="web-01-IP-address"
WEB2_IP="web-02-IP-address"

# Define function to display domain info
domain_info () {
  input_line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
  echo "The subdomain $2 is a $input_line record and points to $3"
}

# Check input arguments
if [ "$#" == 1 ]; then
  # Display info for default subdomains
  domain_info "$1" "www" "$LB_IP"
  domain_info "$1" "lb-01" "$LB_IP"
  domain_info "$1" "web-01" "$WEB1_IP"
  domain_info "$1" "web-02" "$WEB2_IP"
elif [ "$#" == 2 ]; then
  # Display info for specified subdomain
  domain_info "$1" "$2" "$(dig "$2"."$1" +short)"
fi

