#!/usr/bin/env bash
# This script transfres file to the server from the client

if [ "$#" < 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" < 4 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$@":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$@":~/
fi
