#!/usr/bin/env bash
# This script transfres file to the server from the client

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o "$1" "$3@$2":~/
else
	scp -i "$4" -o "$1" "$3@$2":~/
fi
