#!/usr/bin/env bash
# This script installs Nginx, listens o port 80 and returns "Hello World!" on GET request

apt-get -y update
apt-get -y upgrade
apt-get -y install Nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
