#!/usr/bin/env bash
# This script redirects 301 permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
str_sub="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$str_sub/" /etc/nginx/sites-enabled/default

sudo service nginx restart
