#!/usr/bin/env bash
# This script configures Nginx so that its HTTP response contains a # custom header (on web-01 and web-02)


sudo apt-get -y update


sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'


sudo mkdir -p /var/www/html

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /vat/www/html/index_404.html


str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"

str1="\n\tX-Served-By \$localhost"

sudo sed -i "s/server_name _;/$str$str1/" /etc/nginx/sites-enabled/default


str2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$str2$str1/" /etc/nginx/sites-enabled/default


sudo service nginx restart
