#!/usr/bin/env bash
# This script configures Nginx so that its HTTP response contains a 
# custom header (on web-01 and web-02)
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/page_404.html
new_str="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
str1="\n\tadd_header X-Served-By \$hostname;"
str2="\n\terror_page 404 \/page_404.html;\n\tlocation = \/page_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"

sed -i "s/server_name _;/$new_str$str1$str2/" /etc/nginx/sites-enabled/default

service nginx restart
