#!/usr/bin/env bash

# This script installs and configures HAproxy on your lb-01 server

sudo apt-get -y update

sudo apt-get install --no-install-recommends software-properties-common

sudo add-apt-repository ppa:vbernat/haproxy-2.6

sudo apt-get -y install haproxy=2.6.*

# Edit haproxy.cfg file to configure the proxy

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Configure HAProxy
str="
frontend bustlezee-main
  bind *:80
  option forwardfor
  default_backend bustlezee_webservers

backend bustlezee_webservers
  balance roundrobin
  server 176546-web-01 18.206.207.78:80 check
  server 176546-web-02 100.25.14.62:80 check
"

echo $str | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable the haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy start

