#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

sudo apt-get update
sudo apt install ufw
# sudo sed -i 's/IPV6=.*/IPV6=yes' /etc/default/ufw
# sudo ufw disable

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh/tcp
sudo ufw allow http/tcp
sudo ufw allow https/tcp
sudo ufw enable
sudo ufw status verbose

