#!/usr/bin/env bash
# Run Nginx less line
pkill apache2
sudo chmod u+x /etc/nginx/nginx.conf
sudo sed -i 's/user www-data/nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start

