#!/usr/bin/env bash
# Run Nginx as nginx user while listening on port 8080.
pkill apache2
sudo sed -i 's/user www-data/nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod u+x /etc/nginx/nginx.conf
sudo -u nginx service nginx start

